## Problema 1

Crear un Data Frame con columnas Nombre, Edad, Peso, sueldo de 10 personas, y poner en un vector los sueldos de todas la personas

In [1]:
import pandas as pd
import numpy as np

In [3]:
data = ({'Nombre':['Luis', 'Juan', 'Mayra', 'Pedro', 'Ana', 'Moises', 'Laura', 'Oto', 'Nuria', 'Dionisio'], 
                     'Edad':[23,42,40,29,25,30,24,56,44,89], 
                     'Peso':[35.4,35.6,30.5,25.6,40.5,45.6,41.2,50.6,38.9,60.2], 
                     'Sueldo':[5000,10000,9000,5500,6000,8000,2500,7000,8500,4500]})

In [6]:
df = pd.DataFrame(data)
df

Nombre  Edad  Peso  Sueldo
0      Luis    23  35.4    5000
1      Juan    42  35.6   10000
2     Mayra    40  30.5    9000
3     Pedro    29  25.6    5500
4       Ana    25  40.5    6000
5    Moises    30  45.6    8000
6     Laura    24  41.2    2500
7       Oto    56  50.6    7000
8     Nuria    44  38.9    8500
9  Dionisio    89  60.2    4500

In [7]:
sueldos = df['Sueldo'].to_numpy()
sueldos

array([ 5000, 10000,  9000,  5500,  6000,  8000,  2500,  7000,  8500,
        4500], dtype=int64)

## Problema 2

Crear una función con parámetros r y h, para hallar el volumen de un cilindro 

In [1]:
import math

In [8]:
def vol_cilindro(r,h):
    if r < 0 or h < 0:
        return "Los valores de r y h no deben ser negativos."
    volumen = math.pi * r**2 * h
    return volumen

In [6]:
vol_cilindro(-1,1)

'Los valores de r y h no deben ser negativos.'

In [9]:
vol_cilindro(4,3)

150.79644737231007

## Problema 3

Crear una función para encontrar los n-ésimos términos de una serie de Fibonacci

In [20]:
def serie_fibonacci(n):
    if n <= 0:
        return "N debe ser un número positivo."
    elif n == 1:
        return 0
    elif n == 2:
        return 1
    else:
        return serie_fibonacci(n - 2) + serie_fibonacci(n - 1)

In [21]:
serie_fibonacci(10)

34

## Problema 4

Crear dos vectores de orden 10 y aplicar las propiedades mostradas en clase en la sección **Operación básicas de vectores**

In [22]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
y = np.array([10,9,8,7,6,5,4,3,2,1])

In [29]:
#Suma de vectores
print('Suma de vectores usando el símbolo +: \n',x+y)
print(f'Suma de vectores usando add: \n', np.add(x,y))


Suma de vectores usando el símbolo +: 
 [11 11 11 11 11 11 11 11 11 11]
Suma de vectores usando add +: 
 [11 11 11 11 11 11 11 11 11 11]


## Problema 5

Craer un Data Frame con 4 oraciones parecidas al ejemplo aplicativo de PLN y vectorizar

In [38]:
from sklearn.feature_extraction.text import  CountVectorizer
from sklearn.feature_extraction.text import  TfidfVectorizer

In [39]:
datos = pd.DataFrame({'Descripción':['Si Zeus fuera capaz de evitar el mal y quisiera hacerlo, lo haría.','Si Zeus fuera incapaz de evitar el mal,no sería omnipotente; sino quisiera evitar el mal sería malévolo.', 'Zeus no evita el mal.','Si Zeus existe,es omnipotente y no es malévolo.', 'Luego, Zeus no existe.']})
datos

Descripción
0  Si Zeus fuera capaz de evitar el mal y quisier...
1  Si Zeus fuera incapaz de evitar el mal,no serí...
2                              Zeus no evita el mal.
3    Si Zeus existe,es omnipotente y no es malévolo.
4                             Luego, Zeus no existe.

In [45]:
palabras = pd.DataFrame({'Descripción':['Zeus fuera capaz evitar mal quisiera hacerlo haría', 'Zeus fuera incapaz evitar mal sería omnipotente quisiera evitar mal sería malévolo', 'Zeus evita mal', 'Zeus existe omnipotente malévolo', 'Luego Zeus existe']})
palabras

Descripción
0  Zeus fuera capaz evitar mal quisiera hacerlo h...
1  Zeus fuera incapaz evitar mal sería omnipotent...
2                                     Zeus evita mal
3                   Zeus existe omnipotente malévolo
4                                  Luego Zeus existe

In [46]:
contador=CountVectorizer()
vectorizador=TfidfVectorizer()

In [47]:
cantidades=contador.fit_transform(palabras.Descripción)
valores=vectorizador.fit_transform(palabras.Descripción)

In [48]:
print('palabras')
print(vectorizador.get_feature_names_out())
print('cantidades')
print(cantidades)
print('valores')
print(valores)

palabras
['capaz' 'evita' 'evitar' 'existe' 'fuera' 'hacerlo' 'haría' 'incapaz'
 'luego' 'mal' 'malévolo' 'omnipotente' 'quisiera' 'sería' 'zeus']
cantidades
  (0, 14)	1
  (0, 4)	1
  (0, 0)	1
  (0, 2)	1
  (0, 9)	1
  (0, 12)	1
  (0, 5)	1
  (0, 6)	1
  (1, 14)	1
  (1, 4)	1
  (1, 2)	2
  (1, 9)	2
  (1, 12)	1
  (1, 7)	1
  (1, 13)	2
  (1, 11)	1
  (1, 10)	1
  (2, 14)	1
  (2, 9)	1
  (2, 1)	1
  (3, 14)	1
  (3, 11)	1
  (3, 10)	1
  (3, 3)	1
  (4, 14)	1
  (4, 3)	1
  (4, 8)	1
valores
  (0, 6)	0.4215126729847383
  (0, 5)	0.4215126729847383
  (0, 12)	0.3400737705044779
  (0, 9)	0.28229194963946314
  (0, 2)	0.3400737705044779
  (0, 0)	0.4215126729847383
  (0, 4)	0.3400737705044779
  (0, 14)	0.20085304715920277
  (1, 10)	0.23071559833612268
  (1, 11)	0.23071559833612268
  (1, 13)	0.5719320746770253
  (1, 7)	0.28596603733851267
  (1, 12)	0.23071559833612268
  (1, 9)	0.3830295760236044
  (1, 2)	0.46143119667224536
  (1, 4)	0.23071559833612268
  (1, 14)	0.1362643490094122
  (2, 1)	0.7725357304970574
  (2, 

## Problema 6

Crear dos matrices de cualquier orden y aplicar las propiedades de producto de un escalar con un  vector

In [62]:
mat_A = np.array([[5,6],[3,2]])
mat_B = np.array([[3,4],[5,8]])

In [72]:
print('Asociativa')
print('(Matriz A por Matriz B) por 7: \n', (mat_A * mat_B) * 7, '\n es igual a: matriz A por (matriz B por 7) \n', mat_A*(mat_B*7))
print('Distributiva por la izquierda')
print('Multipicar (mat_A + mat_B) por 5: \n', (mat_A + mat_B)*5, '\n es igual a: mat_A * 5 + mat_B * 5 \n', (mat_A * 5 + mat_B*5))
print('Distributiva por la derecha')
print('Multipicar 2 por (mat_A + mat_B): \n', 2*(mat_A + mat_B), '\n es igual a: 2*mat_A + 2*mat_B \n', (2*mat_A + 2*mat_B))
print('Distributiva por la derecha para la suma de vectores')
print('Multipicar mat_A por (5+8): \n', mat_A*(5 + 8), '\n es igual a: mat_A * 5 + mat_A * 8 \n', (5*mat_A + 8*mat_A))

Asociativa
(Matriz A por Matriz B) por 7: 
 [[105 168]
 [105 112]] 
 es igual a: matriz A por (matriz B por 7) 
 [[105 168]
 [105 112]]
Distributiva por la izquierda
Multipicar (mat_A + mat_B) por 5: 
 [[40 50]
 [40 50]] 
 es igual a: mat_A * 5 + mat_B * 5 
 [[40 50]
 [40 50]]
Distributiva por la derecha
Multipicar 2 por (mat_A + mat_B): 
 [[16 20]
 [16 20]] 
 es igual a: 2*mat_A + 2*mat_B 
 [[16 20]
 [16 20]]
Distributiva por la derecha para la suma de vectores
Multipicar mat_A por (5+8): 
 [[65 78]
 [39 26]] 
 es igual a: mat_A * 5 + mat_A * 8 
 [[65 78]
 [39 26]]


In [84]:
# PRODUCTO ESCALAR O PRODUCTO PUNTO
print('Usando @: ',x@y)
print('Usando dot: ',np.dot(x,y))
#PRODUCTO CRUZADO
print('Producto cruzado usando *: ',x*y)

Usando @:  220
Usando dot:  220
Producto cruzado usando *:  [10 18 24 28 30 30 28 24 18 10]


## Problema 7

Hallar la norma Euclidiana y de Manhattan de un vector que usted cree conveniente

In [89]:
a = np.array([0,4,3])
print('Norma euclidiana: ', np.linalg.norm(a,2))
print('Norma Manhattan: ', np.linalg.norm(a,1))

Norma euclidiana:  5.0
Norma Manhattan:  7.0


## Problema 8

Probar si  son ortogonales dos vectores que usted crea conveniente

In [99]:
o_1 = np.array([[5],[4]])
o_2 = np.array([[3],[2]])

cos_theta = (o_1.T@o_2)/(np.linalg.norm(o_1,2) * np.linalg.norm(o_2,2))
cos_theta

array([[0.99624059]])

In [100]:
cos_inversa = np.arccos(cos_theta)
angulo = cos_inversa * ((180)/np.pi)
if angulo == 90:
    print('Los vectores son ortogonales',angulo)
else:
    print('Los vectores no son ortogonales',angulo)

Los vectores no son ortogonales [[4.96974073]]


## Problema 9

Aplicar las propiedades de la  Multiplicación matriz-matriz para las matrices que usted crea conveniente

In [6]:
mat1 = np.array([[2,3],[8,2]])
mat2 = np.array([[4,5],[7,1]])
mat3 = np.array([[6,9],[8,3]])

In [7]:
print('Asociativa')
print('(A*B)*C: \n', (mat1 * mat2) * mat3, '\n es igual a: A(BC) \n', mat1*(mat2*mat3))
print('Multiplicación por un escalar')
print('2*(A*B): \n', 2*(mat1 * mat2), '\n es igual a: (2*A)*B \n', (2*mat1)* mat2)
print('Distributiva')
print('A*(B + C): \n', mat1*(mat2 + mat3), '\n es igual a: A*B + A*C \n', (mat1*mat2 + mat1*mat3))
print('Transpuesta del producto')
print('(A*B)**T: \n', (mat1*mat2).T, '\n es igual a: (B**T)*(A**T) \n', (mat2.T)*(mat1.T))

Asociativa
(A*B)*C: 
 [[ 48 135]
 [448   6]] 
 es igual a: A(BC) 
 [[ 48 135]
 [448   6]]
Multiplicación por un escalar
2*(A*B): 
 [[ 16  30]
 [112   4]] 
 es igual a: (2*A)*B 
 [[ 16  30]
 [112   4]]
Distributiva
A*(B + C): 
 [[ 20  42]
 [120   8]] 
 es igual a: A*B + A*C 
 [[ 20  42]
 [120   8]]
Transpuesta del producto
(A*B)**T: 
 [[ 8 56]
 [15  2]] 
 es igual a: (B**T)*(A**T) 
 [[ 8 56]
 [15  2]]


## Problema 10

Hallar la inversa de una matriz no singular que usted crea conveniente de orden 10X10

In [18]:
matriz_A = np.random.rand(10, 10)

# Verificar si la matriz es no singular
if np.linalg.det(matriz_A) != 0:
    # Inversa de la matriz
    A_inversa = np.linalg.inv(matriz_A)
    
    # Mostrar la matriz inversa
    print("Matriz Inversa: \n", A_inversa)
else:
    print("La matriz no es no singular (su determinante es igual a cero). No se puede calcular la inversa.")

Matriz Inversa: 
 [[ 13.03181688  -8.31139521   3.30906432   4.58010201 -12.02701308
  -14.68220663   8.04851028  -2.49979357  -1.71968917   1.82686953]
 [ -5.55193409   1.57061831  -3.71141329   0.09772841   3.12480185
    3.54808224   0.7573672   -0.94605612   2.08543147   1.26957525]
 [  4.2814675   -2.02324358   0.05718814   1.02896446  -2.75571546
   -5.71975539   2.81655981  -0.31009834  -0.26864274   0.26128736]
 [ -1.48626672  -0.99457403  -0.98705459  -0.32082715   0.86664045
    1.7552606    1.01877778  -0.87438621   1.7611228   -0.22347317]
 [ -5.21236568   3.773465     0.70857825  -2.80160953   3.73589571
    7.56354651  -4.1434043    1.06070811   0.12068265  -1.04224424]
 [ -7.49071887   7.48807174   0.40993174  -4.34557919   9.92109479
    9.99701993  -9.73880883   3.54914147  -0.05850385  -2.38907769]
 [ 12.99320188  -7.87029343   1.8467531    4.29608418 -11.58788648
  -14.19549363   8.34342345  -1.78708637  -3.28635847   2.8577673 ]
 [ -6.36622491   6.22752394   2.16267

## Problema 11 

Crear una función que encuentre los n primeros números perfectos 

In [36]:
def es_numero_perfecto(num):
    suma_divisores = sum([i for i in range(1, num) if num % i == 0])
    return suma_divisores == num

def encontrar_num_perfectos(n):
    numeros_perfectos = []
    num = 2  # primer número perfecto conocido (6)
    
    while len(numeros_perfectos) < n:
        if es_numero_perfecto(num):
            numeros_perfectos.append(num)
        num += 1
    
    return numeros_perfectos

In [35]:
encontrar_num_perfectos(4)

[6, 28, 496, 8128]