In [7]:
import numpy as np
import pandas as pd

#### 1) Crear una matriz de una solo dimensión con numpy utilizando tupla

In [12]:
vector=np.array((3,7,9))
vector

array([3, 7, 9])

#### 2) Crear una matriz de 2-D  con numpy

In [15]:
matriz = np.array([[5, 2, 6],[12, 1, 3]])
matriz

array([[ 5,  2,  6],
       [12,  1,  3]])

#### 3) Acceder a elementos de un arreglo 2-D en Numpy

In [17]:
#obtener el elemento de la fila 1 columna 2
matriz[0,1]

2

In [18]:
#encontrando toda la fila
matriz[1:]

array([[12,  1,  3]])

#### 4) Obtener la forma de un arreglo Numpy 

In [19]:
matriz.shape

(2, 3)

#### 5)  Crear una matriz de orden 2x6 con numpy y mostrar el elemento de la fila 2 y columna 3

In [26]:
import random

In [35]:
mat1=np.random.random((2,6))
mat1

array([[0.34165149, 0.10240034, 0.90922253, 0.48952742, 0.91512998,
        0.4178611 ],
       [0.8738461 , 0.34513323, 0.04690985, 0.36376681, 0.67086165,
        0.41281436]])

In [36]:
mat1[1,2]

0.04690985420427851

In [37]:
mat2 = np.array([[1, 2, 3, 4, 5, 6],
                   [7, 8, 9, 10, 11, 12]])
mat2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [39]:
mat2[1,2]

9

#### 6)  Mostrar mediante un ejemplo las diferencias entre una tupla y una lista

In [2]:
lista = ['Esta', 'es', 1, 'lista']
lista

['Esta', 'es', 1, 'lista']

In [5]:
tupla = (89766, 'Alicia', 'Julio', 1988)
tupla

(89766, 'Alicia', 'Julio', 1988)

7) Crear dos matrices, una de 2x2 y la otra 3x2, reemplazar el elemento de la fila 1 y columna 2 de la primera matriz con el elemento de la fila 2 y columna 1 de la segunda matriz

In [29]:
matriz1 = np.array([[2,4],[5,3]])
print('matriz1: \n', matriz1)
matriz2 = np.array([[5,0],[9,1],[6,8]])
print('matriz2: \n',matriz2)

matriz1: 
 [[2 4]
 [5 3]]
matriz2: 
 [[5 0]
 [9 1]
 [6 8]]


In [20]:
matriz1[0,1]=matriz2[1,0]

In [21]:
matriz1

array([[2, 9],
       [5, 3]])

#### 8) Mover dos elementos de una matriz a otra del ejercicio anterior

In [33]:
#moveremos los 2 valores de la fila 1 de la matriz2 hacia la primera fila de la matriz 1
matriz1[:1]=matriz2[:1]
matriz1

array([[5, 0],
       [5, 3]])

#### 9) Crear una matriz de 4x4 de tipo compleja y luego reemplazar el elemento de la fila 2 y columna 3 por un valor entero

In [41]:
matrizC=np.array([[3,2,15,6],[4,13,2,6],[10,6,19,8],[1,30,2,16]],dtype=complex)
matrizC

array([[ 3.+0.j,  2.+0.j, 15.+0.j,  6.+0.j],
       [ 4.+0.j, 13.+0.j,  2.+0.j,  6.+0.j],
       [10.+0.j,  6.+0.j, 19.+0.j,  8.+0.j],
       [ 1.+0.j, 30.+0.j,  2.+0.j, 16.+0.j]])

In [44]:
matrizC[1,2]= 50
matrizC

array([[ 3.+0.j,  2.+0.j, 15.+0.j,  6.+0.j],
       [ 4.+0.j, 13.+0.j, 50.+0.j,  6.+0.j],
       [10.+0.j,  6.+0.j, 19.+0.j,  8.+0.j],
       [ 1.+0.j, 30.+0.j,  2.+0.j, 16.+0.j]])

#### 10) hacer un ejemplo donde se muestre claramente la eficiencia de un array frente a un bucle

In [45]:
import time

In [56]:
# Sumaremos una lista de números de uno en uno
# Crear un array grande de números
num_elementos = 1000000
array = np.random.rand(num_elementos)
print(array)

[0.7008307  0.86370911 0.49423655 ... 0.47823616 0.64605573 0.24619411]


In [58]:
# Medir el tiempo usando un bucle
inicio_bucle = time.time()
suma_bucle = 0
for num in array:
    suma_bucle += num
fin_bucle = time.time()
# Calcular los tiempos
tiempo_bucle = fin_bucle - inicio_bucle

In [59]:
# Medir el tiempo usando la función de suma de NumPy
inicio_numpy = time.time()
suma_numpy = np.sum(array)
fin_numpy = time.time()
# Calcular los tiempos
tiempo_numpy = fin_numpy - inicio_numpy

In [60]:
# Mostrar los resultados
print(f"Suma usando bucle: {suma_bucle}")
print(f"Tiempo usando bucle: {tiempo_bucle} segundos")

print(f"Suma usando NumPy: {suma_numpy}")
print(f"Tiempo usando NumPy: {tiempo_numpy} segundos")


Suma usando bucle: 500110.272658317
Tiempo usando bucle: 0.4567594528198242 segundos
Suma usando NumPy: 500110.27265832014
Tiempo usando NumPy: 0.0029973983764648438 segundos
